### ISSUE TITLE
Package name is hardcoded

### ISSUE THREAD

**Issue by harshmandan** [ened/flutter_plugin_native_resource#6]
Hey! Nice little utility there!

One problem though, it is hardcoded for your own app it seems.

Using this package results in this error:

```
E/flutter ( 6939): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method 
read on channel asia.ivity.flutter/native_resource/methods)
E/flutter ( 6939): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter ( 6939): <asynchronous suspension>
E/flutter ( 6939): #1      NativeResource.read (package:native_resource/native_resource.dart:37:13)
E/flutter ( 6939): <asynchronous suspension>
E/flutter ( 6939): #2      _WebfrontState._getUrl (package:shopfront/webfront.dart:46:18)
E/flutter ( 6939): <asynchronous suspension>
E/flutter ( 6939):
```

Using it as:

```
 String name = await NativeResource().read(
      androidResourceName: 'app_name',
      iosPlistKey: 'CFBundleIdentifier',
    );
```

**Comment by harshmandan** [comment]
Just had to rebuild the app! 🤦‍♂️ Nice little package though!
